### ISSUE TITLE
Some response validation errors are not skipped as per "response_validation" option

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-openapitools#4]
Hello,

Since last release, I'm getting the following response validation error
`openapi_core.validation.response.exceptions.DataValidationError: DataValidationError: Failed to cast value to object type:...`
even though I'm importing the library with option `response_validation=INFO`

I noticed that in last version there has been an upgrade of the openapi_core package, and noticed in it some error renaming.

I suspect we fail to catch the openapi_core error [here](https://github.com/MarketSquare/robotframework-openapitools/blob/4ce6e97c9c34c4a1a7d53679d792af743d3d7c1f/src/OpenApiDriver/openapi_executors.py#L492)
but I might be on a wrong lead

I'm trying to dig deeper if this is well the case

```
Traceback (most recent call last):
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/OpenApiDriver/openapi_executors.py", line 394, in validate_response
    self._validate_response_against_spec(response)
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/OpenApiDriver/openapi_executors.py", line 488, in _validate_response_against_spec
    self.validate_response_vs_spec(
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/OpenApiLibCore/openapi_libcore.py", line 636, in validate_response_vs_spec
    _ = validate_response(
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/openapi_core/shortcuts.py", line 181, in validate_response
    return OpenAPI(spec, config=config).validate_response(request, response)
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/openapi_core/app.py", line 355, in validate_response
    self.validate_apicall_response(request, response)
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/openapi_core/app.py", line 369, in validate_apicall_response
    self.response_validator.validate(request, response)
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/openapi_core/validation/response/validators.py", line 212, in validate
    raise err
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/openapi_core/validation/response/validators.py", line 61, in _iter_errors
    self._get_data(data, mimetype, operation_response)
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/openapi_core/validation/decorators.py", line 35, in wrapper
    self._raise_error(exc, self.err_cls, f, *args, **kwds)
  File "/Users/Shared/robocorp/ht/a2a55b0_b1f3c24_791b5f1e/lib/python3.9/site-packages/openapi_core/validation/decorators.py", line 58, in _raise_error
    raise init(**kw) from exc
```

Thanks

**Comment by Leemur89** [comment]
root cause might also be on openapi-core, where it used to get response data as str and now it does as bytes...

**Comment by robinmackaij** [comment]
This is most likely to a mime type other than `application/json`. I just merged a fix for that that was tested on an api using `hal+json` and 'problem+json`. I expect this fix to work in other cases also. I plan to release to pypi later today.

**Comment by Leemur89** [comment]
fixed with the new release
